### ISSUE TITLE
The difference between `TitlePageZone` and `RubricLine:title`

### ISSUE THREAD

**Issue by PaulineJac** [SegmOnto/Guidelines#38]
Hello, 
What is the distinction between a `TitlePageZone` and a `MainZone` with a `RubricLine:title`? 
What will be the output XMl TEI code for these elements? 
For example, in this pliego, they lines " La pescatera catalana ... Lo poble baix" must be a Pagezone, right ?
![image](https://user-images.githubusercontent.com/61355979/144209350-ef740617-8668-4182-bb0a-02ab39f30338.png)
But what about the titles on the following pages? 
![image](https://user-images.githubusercontent.com/61355979/144209678-634a3795-085b-4264-b126-ac3030663623.png)
![image](https://user-images.githubusercontent.com/61355979/144209710-00ea129b-51ce-4e62-b44c-9abb77790658.png)
"Lo cansoné de las barraquetas" et "Una per lo poble baix" should be considered as a `TitlePageZone` or just a `RubricLine:title` ? 
Thank you for your help.

**Comment by Jean-Baptiste-Camps** [comment]
Good point, maybe we should drop `TitlePageZone` altogether.

**Comment by gabays** [comment]
In `titlePage` there is _Page_, which is not the case here: it is not the whole page, so it is not a `TitlePage`.
During the discussion yesterday, specialists of old prints agreed that it is important for them, because it keeps very specific data. There is also a computational justification to it (very different font/layout). I would keep it.
`headingLine` (cf. https://github.com/SegmOnto/Guidelines/issues/39) would be perfect.

**Comment by PaulineJac** [comment]
Thank you for your answer
